import { Subject } from "./types";

export const SUBJECTS_SHORT: Subject[] = [
  {
    id: "financial_calc",
    name: "財務会計論（計算）",
    shortName: "財計",
    maxScore: 100,
    passingScore: 40,
    topics: [
      { id: "fin_revenue",       subjectId: "financial_calc", name: "収益認識基準",                     weight: 5 },
      { id: "fin_financial_ins", subjectId: "financial_calc", name: "金融商品会計",                     weight: 5 },
      { id: "fin_consolidation", subjectId: "financial_calc", name: "連結財務諸表",                     weight: 5 },
      { id: "fin_tangible",      subjectId: "financial_calc", name: "有形固定資産・減価償却",           weight: 4 },
      { id: "fin_lease",         subjectId: "financial_calc", name: "リース会計",                       weight: 4 },
      { id: "fin_retirement",    subjectId: "financial_calc", name: "退職給付会計",                     weight: 4 },
      { id: "fin_tax_effect",    subjectId: "financial_calc", name: "税効果会計",                       weight: 4 },
      { id: "fin_merger",        subjectId: "financial_calc", name: "企業結合・事業分離",               weight: 4 },
      { id: "fin_impairment",    subjectId: "financial_calc", name: "固定資産の減損",                   weight: 4 },
      { id: "fin_cashflow",      subjectId: "financial_calc", name: "キャッシュ・フロー計算書",         weight: 4 },
      { id: "fin_intangible",    subjectId: "financial_calc", name: "無形固定資産・研究開発費",         weight: 3 },
      { id: "fin_forex",         subjectId: "financial_calc", name: "外貨換算会計",                     weight: 3 },
      { id: "fin_hedge",         subjectId: "financial_calc", name: "デリバティブ・ヘッジ会計",         weight: 3 },
      { id: "fin_provision",     subjectId: "financial_calc", name: "引当金・負債会計",                 weight: 3 },
      { id: "fin_inventory",     subjectId: "financial_calc", name: "棚卸資産会計",                     weight: 3 },
      { id: "fin_equity",        subjectId: "financial_calc", name: "純資産会計",                       weight: 3 },
      { id: "fin_segment",       subjectId: "financial_calc", name: "セグメント情報",                   weight: 2 },
      { id: "fin_asset_retire",  subjectId: "financial_calc", name: "資産除去債務",                     weight: 3 },
    ],
  },
  {
    id: "financial_theory",
    name: "財務諸表論（理論）",
    shortName: "財理",
    maxScore: 100,
    passingScore: 40,
    topics: [
      { id: "fin_principles",      subjectId: "financial_theory", name: "企業会計原則・概念フレームワーク", weight: 5 },
      { id: "fin_th_recognition",  subjectId: "financial_theory", name: "収益・費用の認識基準（理論）",   weight: 4 },
      { id: "fin_th_assets",       subjectId: "financial_theory", name: "資産・負債の評価基準（理論）",   weight: 4 },
      { id: "fin_th_display",      subjectId: "financial_theory", name: "財務諸表の表示・開示",           weight: 4 },
      { id: "fin_th_policy",       subjectId: "financial_theory", name: "会計方針・見積もりの変更",       weight: 3 },
      { id: "fin_th_ifrs",         subjectId: "financial_theory", name: "IFRS・会計基準の国際的動向",    weight: 3 },
      { id: "fin_th_disclosure",   subjectId: "financial_theory", name: "注記・ディスクロージャー",       weight: 3 },
    ],
  },
  {
    id: "management",
    name: "管理会計論",
    shortName: "管理",
    maxScore: 100,
    passingScore: 40,
    topics: [
      { id: "mgmt_theory",      subjectId: "management", name: "原価計算基準・管理会計理論",      weight: 3 },
      { id: "mgmt_cost_item",   subjectId: "management", name: "費目別原価計算",                  weight: 3 },
      { id: "mgmt_individual",  subjectId: "management", name: "個別原価計算",                    weight: 4 },
      { id: "mgmt_process",     subjectId: "management", name: "総合原価計算",                    weight: 5 },
      { id: "mgmt_standard",    subjectId: "management", name: "標準原価計算",                    weight: 5 },
      { id: "mgmt_direct",      subjectId: "management", name: "直接原価計算",                    weight: 4 },
      { id: "mgmt_abc",         subjectId: "management", name: "活動基準原価計算（ABC）",         weight: 3 },
      { id: "mgmt_cvp",         subjectId: "management", name: "CVP分析・短期利益計画",           weight: 4 },
      { id: "mgmt_decision",    subjectId: "management", name: "意思決定会計",                    weight: 4 },
      { id: "mgmt_investment",  subjectId: "management", name: "設備投資の経済計算",              weight: 3 },
      { id: "mgmt_budget",      subjectId: "management", name: "予算管理・業績測定",              weight: 4 },
    ],
  },
  {
    id: "audit",
    name: "監査論",
    shortName: "監査",
    maxScore: 100,
    passingScore: 40,
    topics: [
      { id: "audit_concept",    subjectId: "audit", name: "監査の基礎概念",           weight: 4 },
      { id: "audit_risk",       subjectId: "audit", name: "リスク・アプローチ",       weight: 5 },
      { id: "audit_internal",   subjectId: "audit", name: "内部統制の評価",           weight: 4 },
      { id: "audit_plan",       subjectId: "audit", name: "監査計画・監査手続",       weight: 4 },
      { id: "audit_evidence",   subjectId: "audit", name: "監査証拠・実証手続",       weight: 4 },
      { id: "audit_report",     subjectId: "audit", name: "監査報告書",               weight: 3 },
      { id: "audit_quality",    subjectId: "audit", name: "品質管理基準",             weight: 3 },
      { id: "audit_ethics",     subjectId: "audit", name: "倫理規則・独立性",         weight: 4 },
      { id: "audit_it",         subjectId: "audit", name: "IT環境下の監査",           weight: 3 },
      { id: "audit_group",      subjectId: "audit", name: "グループ監査・特殊領域",   weight: 2 },
    ],
  },
  {
    id: "corporate",
    name: "企業法",
    shortName: "企業法",
    maxScore: 100,
    passingScore: 40,
    topics: [
      { id: "corp_establish",   subjectId: "corporate", name: "会社の設立・定款",             weight: 3 },
      { id: "corp_share",       subjectId: "corporate", name: "株式・新株予約権",             weight: 4 },
      { id: "corp_meeting",     subjectId: "corporate", name: "機関設計・株主総会",           weight: 4 },
      { id: "corp_director",    subjectId: "corporate", name: "取締役・取締役会",             weight: 5 },
      { id: "corp_calc",        subjectId: "corporate", name: "計算・配当",                   weight: 4 },
      { id: "corp_reorg",       subjectId: "corporate", name: "組織再編（合併・分割等）",     weight: 4 },
      { id: "corp_bond",        subjectId: "corporate", name: "社債",                         weight: 2 },
      { id: "corp_finlaw",      subjectId: "corporate", name: "金融商品取引法",               weight: 4 },
    ],
  },
];

export const SUBJECTS_ESSAY: Subject[] = [
  ...SUBJECTS_SHORT.map((s) => ({ ...s, passingScore: 0 })),
  {
    id: "tax",
    name: "租税法",
    shortName: "租税",
    maxScore: 100,
    passingScore: 0,
    topics: [
      { id: "tax_income",      subjectId: "tax", name: "所得税法",       weight: 3 },
      { id: "tax_corporate",   subjectId: "tax", name: "法人税法",       weight: 5 },
      { id: "tax_consumption", subjectId: "tax", name: "消費税法",       weight: 4 },
      { id: "tax_other",       subjectId: "tax", name: "その他の税法",   weight: 2 },
    ],
  },
  {
    id: "elective",
    name: "選択科目（経営学）",
    shortName: "選択",
    maxScore: 100,
    passingScore: 0,
    topics: [
      { id: "elect_org",       subjectId: "elective", name: "経営組織論",                 weight: 4 },
      { id: "elect_strategy",  subjectId: "elective", name: "経営戦略論",                 weight: 4 },
      { id: "elect_finance",   subjectId: "elective", name: "財務管理論（コーポレートファイナンス）", weight: 5 },
      { id: "elect_marketing", subjectId: "elective", name: "マーケティング管理論",       weight: 3 },
      { id: "elect_hr",        subjectId: "elective", name: "人的資源管理論",             weight: 3 },
    ],
  },
];

export const getSubjects = (examType: string): Subject[] => {
  if (examType === "essay") return SUBJECTS_ESSAY;
  return SUBJECTS_SHORT;
};
